import { Link } from 'react-router-dom'
import DriverIdentity from '@/components/dashboard/DriverIdentity'
import Button from '@/components/ui/Button'
import Container from '@/components/ui/Container'
import Section from '@/components/ui/Section'
import { circuitRegistry } from '@/data/circuitRegistry'
import { driverRegistry } from '@/data/driverRegistry'
import type { ReactNode } from 'react'

const features = [
  ['01', 'Telemetry Analysis', 'Read every braking, throttle, speed, and power signal with a focused engineering workspace.'],
  ['02', 'Driver Comparison', 'Put two laps under the same microscope and make every difference visible.'],
  ['03', 'Circuit Intelligence', 'Bring circuit geometry, corners, and live car position into the same view.'],
  ['04', 'Engineering Reports', 'Export a concise race-engineering record from the live session state.'],
  ['05', 'Session Explorer', 'Move from a season to the lap that matters through a precise selection flow.'],
] as const

export default function LandingShowcase(): ReactNode {
  return <>
    <Section spacing="none" className="border-y border-[var(--color-border)] bg-[var(--color-background-secondary)]"><Container><div className="grid divide-y divide-[var(--color-border)] md:grid-cols-4 md:divide-x md:divide-y-0">{[['24', 'Circuits'], ['22', 'Drivers'], ['Raw', 'Telemetry samples'], ['One', 'Engineering workspace']].map(([value, label]) => <div key={label} className="px-[var(--space-md)] py-[var(--space-xl)]"><p className="[font-family:var(--font-family-mono)] text-[var(--font-size-heading-3)] font-[var(--font-weight-semibold)] text-[var(--color-text-primary)]">{value}</p><p className="mt-[var(--space-xs)] rc-type-caption">{label}</p></div>)}</div></Container></Section>
    <Section id="features" spacing="2xl"><Container><div className="max-w-2xl"><p className="rc-type-caption text-[var(--color-f1-red)]">Built for the debrief</p><h2 className="rc-type-page-title mt-[var(--space-sm)]">The engineering layer of Formula One.</h2></div><div className="mt-[var(--space-2xl)] space-y-[var(--space-sm)]">{features.map(([index,title,description]) => <article key={title} className="group grid gap-[var(--space-md)] border border-[var(--color-border)] bg-[var(--color-surface)] p-[var(--space-lg)] transition-[transform,border-color,background-color] duration-[var(--duration-normal)] hover:-translate-y-0.5 hover:border-[var(--color-f1-red)] hover:bg-[var(--color-surface-hover)] md:grid-cols-[5rem_minmax(0,1fr)_minmax(0,1.25fr)] md:items-center"><span className="[font-family:var(--font-family-mono)] text-[var(--font-size-caption)] text-[var(--color-f1-red)]">{index}</span><h3 className="rc-type-section-title">{title}</h3><p className="rc-type-body">{description}</p></article>)}</div></Container></Section>
    <Section id="drivers" spacing="2xl" background="secondary"><Container><div className="flex flex-wrap items-end justify-between gap-[var(--space-lg)]"><div><p className="rc-type-caption text-[var(--color-f1-red)]">The grid</p><h2 className="rc-type-page-title mt-[var(--space-sm)]">Drivers, in context.</h2></div><Link to="/drivers"><Button variant="secondary">View Drivers</Button></Link></div><div className="mt-[var(--space-xl)] grid gap-[var(--space-md)] md:grid-cols-3">{driverRegistry.slice(0,3).map((driver) => <article key={driver.id} className="rc-card border-l-2" style={{ borderLeftColor: driver.accentColor }}><DriverIdentity driver={driver} /><p className="mt-[var(--space-lg)] rc-type-body">Driver identity, constructor context, and a direct route into live analysis.</p></article>)}</div></Container></Section>
    <Section id="circuits" spacing="2xl"><Container><div className="flex flex-wrap items-end justify-between gap-[var(--space-lg)]"><div><p className="rc-type-caption text-[var(--color-f1-red)]">The calendar</p><h2 className="rc-type-page-title mt-[var(--space-sm)]">Every circuit has a signature.</h2></div><Link to="/circuits"><Button variant="secondary">Explore Circuits</Button></Link></div><div className="mt-[var(--space-xl)] grid gap-[var(--space-md)] md:grid-cols-3">{circuitRegistry.slice(0,3).map((circuit) => <article key={circuit.id} className="rc-card"><p className="rc-type-caption">Round {String(circuit.calendarRound).padStart(2,'0')} · {circuit.country}</p><h3 className="rc-type-card-title mt-[var(--space-md)]">{circuit.name}</h3><dl className="mt-[var(--space-xl)] grid grid-cols-2 border-t border-[var(--color-border)] pt-[var(--space-md)]"><div><dt className="rc-metric-label">Length</dt><dd className="mt-[var(--space-xs)] text-[var(--font-size-small)]">{circuit.length}</dd></div><div><dt className="rc-metric-label">Corners</dt><dd className="mt-[var(--space-xs)] text-[var(--font-size-small)]">{circuit.officialCornerCount}</dd></div></dl><Link to={`/dashboard?circuit=${encodeURIComponent(circuit.name)}`} className="mt-[var(--space-lg)] inline-flex text-[var(--font-size-small)] font-[var(--font-weight-medium)] text-[var(--color-f1-red)]">Analyze Circuit →</Link></article>)}</div></Container></Section>
    <Section id="workspace-preview" spacing="2xl" background="secondary"><Container><div className="grid gap-[var(--space-xl)] lg:grid-cols-[minmax(0,0.8fr)_minmax(0,1.2fr)] lg:items-center"><div><p className="rc-type-caption text-[var(--color-f1-red)]">Engineering workspace</p><h2 className="rc-type-page-title mt-[var(--space-sm)]">One clear view of the lap.</h2><p className="mt-[var(--space-lg)] rc-type-body">A purpose-built environment for session context, telemetry traces, circuit position, comparison, and export.</p><Link to="/dashboard" className="mt-[var(--space-xl)] inline-block"><Button>Launch Workspace</Button></Link></div><div aria-label="Engineering workspace preview" className="border border-[var(--color-border)] bg-[var(--color-background)] p-[var(--space-md)] shadow-[var(--shadow-md)]"><div className="grid grid-cols-[4rem_minmax(0,1fr)] gap-[var(--space-sm)]"><div className="min-h-64 border border-[var(--color-border)] bg-[var(--color-background-secondary)]"/><div className="grid gap-[var(--space-sm)]"><div className="h-12 border border-[var(--color-border)] bg-[var(--color-surface)]"/><div className="grid min-h-48 grid-cols-3 gap-[var(--space-sm)]"><div className="col-span-2 border border-[var(--color-border)] bg-[var(--color-surface)]"/><div className="border border-[var(--color-border)] bg-[var(--color-surface)]"/></div></div></div></div></div></Container></Section>
    <Section id="about" spacing="2xl"><Container><div className="border-y border-[var(--color-border)] py-[var(--space-2xl)] text-center"><p className="rc-type-caption text-[var(--color-f1-red)]">RaceCraft</p><h2 className="rc-type-display mx-auto mt-[var(--space-md)] max-w-4xl text-[clamp(2.5rem,7vw,var(--font-size-display))]">Ready to Think Like an Engineer?</h2><div className="mt-[var(--space-xl)] flex flex-wrap justify-center gap-[var(--space-sm)]"><Link to="/dashboard"><Button size="lg">Launch Dashboard</Button></Link><a href="https://github.com" target="_blank" rel="noreferrer"><Button size="lg" variant="secondary">GitHub</Button></a></div></div></Container></Section>
  </>
}
