import type { DashboardView } from '@/components/dashboard/Sidebar'
import type { SessionReportState } from '@/components/dashboard/SessionReportExporter'

export interface EngineeringReport {
  fileStem: string
  title: string
  lines: string[]
}

function value(item: string | number | null | undefined): string { return item === null || item === undefined || item === '' ? 'Unavailable' : String(item) }

export function generateEngineeringReport(state: SessionReportState, activeView: DashboardView): EngineeringReport {
  const telemetry = state.primaryTelemetry ?? []
  const topSpeed = telemetry.length ? Math.max(...telemetry.map((sample) => sample.speed)) : null
  const averageSpeed = telemetry.length ? telemetry.reduce((total, sample) => total + sample.speed, 0) / telemetry.length : null
  const maxThrottle = telemetry.length ? Math.max(...telemetry.map((sample) => sample.throttle)) : null
  const maxBrake = telemetry.some((sample) => sample.brake) ? 'ON' : 'OFF'
  const gearChanges = telemetry.reduce((total, sample, index) => total + Number(index > 0 && sample.gear !== telemetry[index - 1].gear), 0)
  const primaryLap = state.primaryLap
  const secondaryLap = state.secondaryLap
  const notes = state.insights.slice(0, 4).map((insight) => `${insight.title}: ${insight.explanation}`)
  const lines = [
    'RaceCraft Engineering Report',
    `Generated: ${new Date().toLocaleString()}`,
    `Workspace: ${activeView.replaceAll('-', ' ')}`,
    '', 'Session',
    `Driver: ${value(state.primaryDriver?.fullName ?? state.primarySelection.driver)}`,
    `Secondary Driver: ${state.comparisonEnabled ? value(state.secondaryDriver?.fullName ?? state.secondarySelection.driver) : 'Comparison disabled'}`,
    `Season: ${value(state.primarySelection.season)}`,
    `Grand Prix: ${value(state.primarySelection.event)}`,
    `Session: ${value(state.primarySelection.session)}`,
    `Lap: ${value(primaryLap?.lapNumber)}`,
    `Tyre: ${value(primaryLap?.tyreCompound)}`,
    `Lap Time: ${value(primaryLap?.lapTime)}`,
  ]
  if (activeView === 'telemetry' || activeView === 'lap-analysis' || activeView === 'driver-comparison' || activeView === 'brake-comparison') lines.push('', 'Telemetry Summary', `Top Speed: ${topSpeed === null ? 'Unavailable' : `${topSpeed.toFixed(1)} km/h`}`, `Average Speed: ${averageSpeed === null ? 'Unavailable' : `${averageSpeed.toFixed(1)} km/h`}`, `Maximum Throttle: ${maxThrottle === null ? 'Unavailable' : `${maxThrottle.toFixed(0)}%`}`, `Maximum Brake: ${maxBrake}`, `Gear Changes: ${gearChanges}`, `Samples: ${telemetry.length || 'Unavailable'}`)
  if (activeView === 'sector-analysis' || activeView === 'driver-comparison') lines.push('', 'Sector Summary', `S1: ${value(primaryLap?.sector1Time)}`, `S2: ${value(primaryLap?.sector2Time)}`, `S3: ${value(primaryLap?.sector3Time)}`, `Total: ${value(primaryLap?.lapTime)}`, `Secondary Total: ${state.comparisonEnabled ? value(secondaryLap?.lapTime) : 'Comparison disabled'}`)
  if (activeView === 'circuit-analysis' || activeView === 'circuit-information' || activeView === 'corner-analysis') lines.push('', 'Circuit Summary', `Circuit: ${value(state.circuit?.circuitName)}`, `Country: ${value(state.circuit?.country)}`, `Location: ${value(state.circuit?.location)}`, `Length: ${value(state.circuit?.circuitLength)}`, `Corners: ${value(state.circuit?.numberOfCorners)}`, `Selected Corner: ${state.selectedCorner ? `Turn ${state.selectedCorner.cornerNumber}` : 'Unavailable'}`)
  lines.push('', 'Engineering Notes', ...(notes.length ? notes : ['No engineering notes are available for the current workspace.']), '', 'Generated by RaceCraft', 'Version Alpha')
  const driver = (state.primaryDriver?.abbreviation ?? state.primarySelection.driver ?? 'Session').replace(/[^a-z0-9_-]/gi, '_')
  return { title: 'RaceCraft Engineering Report', fileStem: `RaceCraft_Report_${driver}_${primaryLap?.lapNumber ?? 'Lap'}`, lines }
}
